version: '3'
services:
  otel-server:
    container_name: otel-server
    image: otel/opentelemetry-collector-contrib:0.88.0
    restart: always
    command:
      - --config=/etc/otelcol-contrib/config.yml
    volumes:
      - ./docker/otel-collector-server/config.yml:/etc/otelcol-contrib/config.yml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension

  otel-client:
    container_name: otel-client
    image: otel/opentelemetry-collector-contrib:0.88.0
    restart: always
    command:
      - --config=/etc/otelcol-contrib/config.yml
    volumes:
      - ./docker/otel-collector-client/config.yml:/etc/otelcol-contrib/config.yml
      - ./docker/resources/sample.log:/var/log/app/sample.log

  loki:
    container_name: loki
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - ./docker2/grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - "3000:3000"