version: '3'
services:
  otel-server:
    container_name: otel-server
    image: otel/opentelemetry-collector-contrib:0.88.0
    restart: always
    command:
      - --config=/etc/otelcol-contrib/config.yml
    volumes:
      - ./docker/otel-collector-server/config.yml:/etc/otelcol-contrib/config.yml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension

  otel-regex-client:
    container_name: otel-regex-client
    image: otel/opentelemetry-collector-contrib:0.88.0
    restart: always
    command:
      - --config=/etc/otelcol-contrib/config.yml
    volumes:
      - ./docker/otel-collector-regex-client/config.yml:/etc/otelcol-contrib/config.yml
      - ./docker/resources/sample.log:/var/log/app/sample.log

  otel-json-client:
    container_name: otel-json-client
    image: otel/opentelemetry-collector-contrib:0.88.0
    restart: always
    command:
      - --config=/etc/otelcol-contrib/config.yml
    volumes:
      - ./docker/otel-collector-json-client/config.yml:/etc/otelcol-contrib/config.yml
      - ./docker/resources/sample-json.log:/var/log/app/sample.log

  otel-soph-regex-client:
    container_name: otel-soph-regex-client
    image: otel/opentelemetry-collector-contrib:0.88.0
    restart: always
    command:
      - --config=/etc/otelcol-contrib/config.yml
    volumes:
      - ./docker/otel-soph-regex-client/config.yml:/etc/otelcol-contrib/config.yml
      - ./docker/resources/soph-regex.log:/var/log/app/soph-regex.log
    environment:
      - HOSTNAME=${HOSTNAME}

  otel-h1-regex-client:
    container_name: otel-h1-regex-client
    image: otel/opentelemetry-collector-contrib:0.88.0
    restart: always
    command:
      - --config=/etc/otelcol-contrib/config.yml
    volumes:
      - ./docker/otel-h1-regex-client/config.yml:/etc/otelcol-contrib/config.yml
      - ./docker/resources/h1-regex.log:/var/log/app/h1-regex.log
    environment:
      - HOSTNAME=${HOSTNAME}

  otel-agent-regex-multi-client:
    container_name: otel-agent-regex-multi-client
    image: otel/opentelemetry-collector-contrib:0.88.0
    restart: always
    command:
      - --config=/etc/otelcol-contrib/config.yml
    volumes:
      - ./docker/otel-agent-regex-multi-client/config.yml:/etc/otelcol-contrib/config.yml
      - ./docker/resources/agent-regex-multi.log:/var/log/app/agent-regex-multi.log
    environment:
      - HOSTNAME=${HOSTNAME}

  otel-combined-parser:
    container_name: otel-combined-parser
    image: otel/opentelemetry-collector-contrib:0.88.0
    restart: always
    command:
      - --config=/etc/otelcol-contrib/config.yml
    volumes:
      - ./docker/otel-combined-parser/config.yml:/etc/otelcol-contrib/config.yml
      - ./docker/resources:/var/log/app
    environment:
      - HOSTNAME=${HOSTNAME}

  loki:
    container_name: loki
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - ./docker2/grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - "3000:3000"