receivers:
  filelog:
    include: [/var/log/app/soph-regex.log]
    start_at: beginning
    operators:
      - type: regex_parser
        regex: '^ *(?P<sev>[a-z]*) : (?P<service_info>.*\)) : \[(?P<time>\d{4}\/\d{2}\/\d{2}-\d{2}:\d{2}:\d{2}.\d{3})] : (?P<msg>.*)$'
        timestamp:
          parse_from: attributes.time
          layout: '%Y/%m/%d-%H:%M:%S.%L'
        severity:
          parse_from: attributes.sev

    resource:
      deployment.env: "dev"
      service.name: "hydra"
      service.version: "1.0.1"
      host.name: ${env:HOSTNAME}
      file.name: attributes.log.file.name

    attributes:

processors:

  #  resource:
  #    attributes:
  #      - action: insert
  #        key: os.name
  #        value: ${env:os.name}
  #      - action: insert
  #        key: hostname
  #        value: ${HOSTNAME}
    # need to get hostname into attributes

  attributes:
    actions:
      - action: delete
        key: log.file.name

  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
          #        value: [deployment.env, service.name, host.name, file.name]
        value: file.name, deployment.env


  batch:

exporters:
  otlphttp:
    endpoint: http://otel-collector:4318

  debug:

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [attributes, resource]
      exporters: [debug, otlphttp]